services:
  - type: web
    name: mplads-api
    env: python
    region: singapore
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Mplads%402026!@db.fcpwrmzviqrhsdgelwmk.supabase.co:5432/postgres
      - key: DIRECT_URL
        value: postgresql://postgres:Mplads%402026!@db.fcpwrmzviqrhsdgelwmk.supabase.co:5432/postgres
      - key: JWT_SECRET_KEY
        value: mplads_secret_key_2026_super_secure
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHONPATH
        value: .
